### ISSUE TITLE
How to run？

### ISSUE THREAD

**Issue by wanguangxi** [staywithme23/lipreading-by-convolutional-neural-network-keras#6]
would you mind priovide the complete files contianed in this project？I have met a question：**Using TensorFlow backend.
WARNING:tensorflow:From /home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:321: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:634: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:491: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:2866: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

Traceback (most recent call last):
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for 'MaxPool_1' (op: 'MaxPool') with input shapes: [?,1,87,128].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/main.py", line 15, in <module>
    import predict as pred
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/predict.py", line 16, in <module>
    model = vggmodel.create_model(175, 175)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/vggmodel.py", line 20, in create_model
    model.add(MaxPooling2D((2, 2), strides=(2, 2)))
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/models.py", line 332, in add
    output_tensor = layer(self.outputs[0])
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/layers/pooling.py", line 160, in call
    dim_ordering=self.dim_ordering)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/layers/pooling.py", line 210, in _pooling_function
    pool_mode='max')
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2866, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 3815, in max_pool
    name=name)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 5674, in max_pool
    data_format=data_format, name=name)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/home/eric/PycharmProjects/lip-reading-cnn-lstm/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'MaxPool_1' (op: 'MaxPool') with input shapes: [?,1,87,128].**

**Comment by Muskan2708** [comment]
Hey! Did you get solution to this problem ? If yes then can you please help me too?
